baseURL: https://zhenghe.hu
title: Zheng He Hu
Author: 
  name: Zheng He Hu
theme: tale-hugo
disablePathToLower: true
enableGitInfo: true
enableEmoji: true
menu:
  main:
  - identifier: notes
    name: Notes
    url: /notes/
    weight: 0

params:
  social:
  - name: email
    url: "mailto:hello@zhenghe.hu"
  - name: twitter
    url: https://twitter.com/aeonzh
  - name: github
    url: https://github.com/aeonzh
